### ISSUE TITLE
result of ufbx_evaluate_transform

### ISSUE THREAD

**Issue by HeadReaper-hc** [ufbx/ufbx#137]
Hi,
   What's the result of function ufbx_evaluate_transform, the transform of node to world or node to parent?

**Comment by bqqbarbhg** [comment]
Heya!

Whelp I thought I had fixed this documentation issue but it seems to have got lost somewhere. The result is the node-to-parent transform, specifically it should be equivalent to `ufbx_node.local_transform`, just animated.

**Comment by HeadReaper-hc** [comment]
@bqqbarbhg Thank you for your reply.
I use following code to get local euler angle for every node in every frame (same as angles in bvh file), but the result is total wrong.  Can you help me to check the code whether it is right?

`void curr_animation(ufbx_scene *scene, ufbx_anim *anim, std::ofstream& ofs) {
    std::cout<<"begin: "<<anim->time_begin<<", end: "<<anim->time_end<<std::endl;

    for(double time = anim->time_begin; time < anim->time_end; time += 0.033333) {

        for (const ufbx_node* scene_node: scene->nodes) {

            std::string curr_name = scene_node->name.data;

            ufbx_transform m = ufbx_evaluate_transform(anim, scene_node, time);
            
            Vector3 euler = ufbx_quat_to_euler(m.rotation, ufbx_rotation_order::UFBX_ROTATION_ORDER_XYZ);
    }

//
//    ufbx_free_baked_anim(bake);
}`

**Comment by bqqbarbhg** [comment]
That should be correct, the only thing is the rotation order. [This page](https://research.cs.wisc.edu/graphics/Courses/cs-838-1999/Jeff/BVH.html) seems to describe concatenating the rotations as:

```
vR = vYXZ
```

It's a bit confusing as those are multiplied from the right, so it's probably either `UFBX_ROTATION_ORDER_YXZ` or `UFBX_ROTATION_ORDER_ZXY`. Could be something unrelated to that but might be worth a shot. Also note that `ufbx_quat_to_euler()` returns degrees (like FBX uses internally) and not radians.

**Comment by HeadReaper-hc** [comment]
Hi,
     I tried again and I am pretty sure the rotation order is right, but the result is still wrong.
     The result is in the following pic. The left is the orginal, right is my result from ufbx. 
     Have you export the local euler angle to bvh file or check the result in any situation?
     
![ufbx-res](https://github.com/ufbx/ufbx/assets/42986202/51926848-43ca-49f3-ba0f-1f37b33ef9ae)

**Comment by HeadReaper-hc** [comment]
@bqqbarbhg 
Can I send you the FBX file so that you can help me check if the motion information can be read correctly through UFBX?

**Comment by bqqbarbhg** [comment]
Yeah sure! You can either upload it here if it's public or send it to `bqqbarbhg [at] gmail.com`, though I can't do much more than give a cursory look that it works, unless it's broken of course (which honestly I assume is quite unlikely :D)

**Comment by bqqbarbhg** [comment]
> The fbx file is sent to your email. By the way,

Thanks, got it!

> is your test code in this depository?

Yeah but currently it's a bit messy, it's spread in the files:

- Main executable used for loading the test cases: [test/check_fbx.c](https://github.com/ufbx/ufbx/blob/master/test/check_fbx.c)
- .obj diffing implemented in: [test/testing_utils.h](https://github.com/ufbx/ufbx/blob/master/test/testing_utils.h)
- Python script for going through a dataset: [test/check_dataset.py](https://github.com/ufbx/ufbx/blob/master/misc/check_dataset.py)

The dataset is not included in the repository though, you can see from [CI logs](https://github.com/ufbx/ufbx/actions/runs/8975477201/job/24676421145) what the commands and .json files look like, but the dataset itself is too big for me to host as a single download.

**Comment by bqqbarbhg** [comment]
The model seems to load correctly in ufbx, tested it via [Godot Dev 4.3](https://godotengine.org/download/archive/4.3-dev6/), which has ufbx for importing. The materials seemed to be a bit messed up but I think that's an Godot issue.

The file had two animations: "Take 001" seems to be just a T-pose and "mixamo_com" looked correct.

**Comment by HeadReaper-hc** [comment]
Got it and thanks again. I will check my code  again.

**Comment by bqqbarbhg** [comment]
Looked at the BVH format a bit for fun and it seems to be a neat simple format so I thought I might make an example for it.

I'll still need to think how "fancy" I want to make it but I have an experimental version here in Gist [bqqbarbhg/fbx2bvh.c](https://gist.github.com/bqqbarbhg/ea4141fc835b5423d0fcc5b54945d36e) if you want to use it to debug your implementation.

At least on my testing using the following command produced a working result in Blender:

```bash
fbx2gltf greeting.fbx -o greeting.bvh --root mixamorig:Hips --anim mixamo.com
```

Using any other rotation order than `UFBX_ROTATION_ORDER_YXZ` seemed to result in an incorrect animation.

**Comment by HeadReaper-hc** [comment]
@bqqbarbhg Yeah, your code is indeed working, which really solves my problem. I think it must be because I didn't understand the correct rotation order. I will learn from your code to correct my mistakes. Thank you very much for your help and time.

**Comment by HeadReaper-hc** [comment]
@bqqbarbhg 
Hi,
    I found the rest pose of your output is different from blender's bvh output. You can check this with Edit Mode in blender.
    So I made a little change based on your code and now it has a normal rest pose display. Besides, it can support any rotation
    order now， no longer necessarily requiring it to be 'UFBX_ROTATION_ORDER_YXZ'.
    The changed code is in here 
[fbx2bvh_change.zip](https://github.com/ufbx/ufbx/files/15414742/fbx2bvh_change.zip)

**Comment by bqqbarbhg** [comment]
Nice! Yeah I didn't take any rest pose stuff into account. Thanks for sharing the fixes! I'll still need to think what would be the best balance of simplicity and correctness for a BVH conversion example, as the bind pose fixes make it a bit harder to follow.

**Comment by HeadReaper-hc** [comment]
Hi,
    Sorry to bother you again @bqqbarbhg. I want to know if ufbx supports all versions of fbx, such as fbx7500 and fbx7700, because I found that the bvh rest pose output when using fbx7500 is correct, while using fbx7700 is incorrect

**Comment by bqqbarbhg** [comment]
Heya, no worries! ufbx should support all versions of FBX, it's been tested with all kind of versions between 3000-7800 and I haven't seen any bind pose differences between FBX 7500 and 7700.

There is a known issue that sometimes `ufbx_node.bind_pose` values are incorrect, but that's due to exporters writing bad data. The other way of getting bind poses is getting the difference between two successive `ufbx_skin_cluster` `bind_to_world` matrices, but that is pretty complicated. I've implemented this for example in [Godot](https://github.com/godotengine/godot/blob/be56cab58c056c074d1e02cd0b38641204e39f41/modules/fbx/fbx_document.cpp?ts=4#L374-L421).

But yeah, bind poses are kind of messy in FBX. In the earlier code you sent you derived the bind poses from the initial node positions, which are not guaranteed to be in bind pose. Depending on your content you might be able to get away with using something like [this](https://github.com/ufbx/ufbx/blob/c8c9a0bbf757127ca95a34eb1295ba4c16e928af/test/check_fbx.c?ts=4#L524-L536) to resolve the bind poses, just ignore the transform override stuff, that's only for testing.

Anyways, bind poses are still kind of half-baked in ufbx and it really doesn't help that exporters sometimes write garbage data and there's the issue that one bone may have multiple bind poses (ie. imagine body skinned in A pose, shirt skinned in T pose, which is allowed). Hopefully you can get something out of this ramble, otherwise feel free to let me know if there seems to be a clear ufbx-side bug with those!

**Comment by HeadReaper-hc** [comment]
Hi,
   Thank you for your patient answer. I tested the two methods you provided, and the sample code in godot can obtain the correct bind pose. Unfortunately, there seems to be some issues with the output animation. However, the sample code in check_fbx.c still cannot obtain the correct bind pose. The incorrect fbx was created through Maya, and importing blender usually requires the use of the better fbx plugin. I will temporarily give up fixing this issue. At least for now, the correct bvh file can be output for the fbx that can be displayed normally in blender. Thank you very much for your help during this period.
